#!/bin/sh
xdg-mime install /tmp/spritefont.xml --novendor

if [ -f /usr/share/applications/Spritefont\ Editor.desktop ]
then
	rm /usr/share/applications/Spritefont\ Editor.desktop
fi
echo "[Desktop Entry]\nVersion=1.0\nEncoding=UTF-8\nName=Spritefont Editor\nGenericName=Spritefont Editor\nComment=Used to create Microsoft .spritefont files\nExec=sfeditor %F\nTryExec=sfeditor\nIcon=sf-application\nStartupNotify=true\nTerminal=false\nType=Application\nMimeType=text/spritefont;\nCategories=Development;" >> /usr/share/applications/Spritefont\ Editor.desktop

